# Generated by Django 5.1.5 on 2025-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('FD', 'Fixed Deposits'), ('INV', 'Investments'), ('BANK', 'Banking')], default='FD', max_length=10),
        ),
    ]
